# Copyright (c) 2026, BuFf0k and contributors
# For license information, please see license.txt

import frappe

IR_CANONICAL_SIDEBAR = "Industrial Relations"

IR_WORKSPACE_NAMES = {
    "Disciplinary Action",
    "IR General",
    "IR Setup",
    "IR Training",
    "IR Attendance"
}

def cleanup_autogen_workspaces_sidebars_and_icons():
    # Remove autogenerated per Workspace Sidebar and Icon documents caused by version-16
    sidebars = frappe.get_all(
        "Workspace Sidebar",
        filters={"standard": 0},
        fields=["name", "standard"],
        limit=500,
    )

    for sb in sidebars:
        name = sb.name
        if name == IR_CANONICAL_SIDEBAR:
            continue
        if name in IR_WORKSPACE_NAMES or name.startswith("IR "):
            frappe.delete_doc("Workspace Sidebar", name, force=1)

    icons = frappe.get_all(
        "Desktop Icon",
        fields=["name", "app", "type", "link_type", "link_to", "route"],
        limit=1000,
    )

    for ic in icons:
        name = ic.name
        if getattr(ic, "app", None) == "ir":
            continue

        if name in IR_WORKSPACE_NAMES or name.startswith("IR "):
            frappe.delete_doc("Desktop Icon", name, force=1)

    frappe.db.commit()
